### ISSUE TITLE
TPSMM 转换后和官方的输出差别很大

### ISSUE THREAD

**Issue by hhuiwang** [TalkUHulk/Image-Animation-Turbo-Boost#1]
您好，TPSMM转换后的ONNX模型和官方的输出差别很大，请问您是否有想法能尽量让其结果和官方的结果一致呢。

**Comment by TalkUHulk** [comment]
> 您好，TPSMM转换后的ONNX模型和官方的输出差别很大，请问您是否有想法能尽量让其结果和官方的结果一致呢。

不一致主要集中在dense_motion_network，原始网络有些op不支持，比如torch.inverse，我使用了其他方法近似，结果不是完全对齐的，测试平均误差9e-5，最大误差平均～0.4339
<img width="1040" alt="image" src="https://user-images.githubusercontent.com/18474163/175016264-6a355ad8-e31d-4af7-bd06-3f4b79a094cc.png">
<img width="720" alt="image" src="https://user-images.githubusercontent.com/18474163/175016378-5fe4dfe0-2044-4b7f-bcfd-328ddb4e23b6.png">

**Comment by hhuiwang** [comment]
> > 您好，TPSMM转换后的ONNX模型和官方的输出差别很大，请问您是否有想法能尽量让其结果和官方的结果一致呢。
> 
> 不一致主要集中在dense_motion_network，原始网络有些op不支持，比如torch.inverse，我使用了其他方法近似，结果不是完全对齐的，测试平均误差9e-5，最大误差平均~0.4339 <img alt="图像" width="1040" src="https://user-images.githubusercontent.com/18474163/175016264-6a355ad8-e31d-4af7-bd06-3f4b79a094cc.png"> <img alt="图像" width="720" src="https://user-images.githubusercontent.com/18474163/175016378-5fe4dfe0-2044-4b7f-bcfd-328ddb4e23b6.png">

感谢您的回复。是我表达得不够清楚，不好意思。我的意思是您的项目得到的结果是这样的：
![generated_onnx 00_00_00-00_00_30](https://user-images.githubusercontent.com/33827101/175121804-ae1e1a4b-a6d5-47e1-92b9-4b8b2bfade05.gif)

下面是官方项目得到的结果：
![result 00_00_00-00_00_30](https://user-images.githubusercontent.com/33827101/175121899-cf3ee2ea-a27d-44c1-8083-bea2fb2f9904.gif)

发现官方的项目有三种模式，实在不知道怎么把这个转换到您的项目上以保持一致，再次感谢您的帮助。
![202206230340061](https://user-images.githubusercontent.com/33827101/175123178-fe69bd0d-f6fa-45c2-9a81-f4fd92fae421.jpg)

**Comment by TalkUHulk** [comment]
使用的standard

**Comment by TalkUHulk** [comment]
> > > 您好，TPSMM转换后的ONNX模型和官方的输出差别很大，请问您是否有想法能尽量让其结果和官方的结果一致呢。
> > 
> > 
> > 不一致主要集中在dense_motion_network，原始网络有些op不支持，比如torch.inverse，我使用了其他方法近似，结果不是完全对齐的，测试平均误差9e-5，最大误差平均~0.4339 <img alt="图像" width="1040" src="https://user-images.githubusercontent.com/18474163/175016264-6a355ad8-e31d-4af7-bd06-3f4b79a094cc.png"> <img alt="图像" width="720" src="https://user-images.githubusercontent.com/18474163/175016378-5fe4dfe0-2044-4b7f-bcfd-328ddb4e23b6.png">
> 
> 感谢您的回复。是我表达得不够清楚，不好意思。我的意思是您的项目得到的结果是这样的： ![generated_onnx 00_00_00-00_00_30](https://user-images.githubusercontent.com/33827101/175121804-ae1e1a4b-a6d5-47e1-92b9-4b8b2bfade05.gif) [ ](https://user-images.githubusercontent.com/33827101/175121804-ae1e1a4b-a6d5-47e1-92b9-4b8b2bfade05.gif) ![generated_onnx 00_00_00-00_00_30](https://user-images.githubusercontent.com/33827101/175121804-ae1e1a4b-a6d5-47e1-92b9-4b8b2bfade05.gif) [ ](https://user-images.githubusercontent.com/33827101/175121804-ae1e1a4b-a6d5-47e1-92b9-4b8b2bfade05.gif)
> 
> 下面是官方项目得到的结果： ![result 00_00_00-00_00_30](https://user-images.githubusercontent.com/33827101/175121899-cf3ee2ea-a27d-44c1-8083-bea2fb2f9904.gif) [ ](https://user-images.githubusercontent.com/33827101/175121899-cf3ee2ea-a27d-44c1-8083-bea2fb2f9904.gif) ![result 00_00_00-00_00_30](https://user-images.githubusercontent.com/33827101/175121899-cf3ee2ea-a27d-44c1-8083-bea2fb2f9904.gif) [ ](https://user-images.githubusercontent.com/33827101/175121899-cf3ee2ea-a27d-44c1-8083-bea2fb2f9904.gif)
> 
> 发现官方的项目有三种模式，实在不知道怎么把这个转换到您的项目上以保持一致，再次感谢您的帮助。 ![202206230340061](https://user-images.githubusercontent.com/33827101/175123178-fe69bd0d-f6fa-45c2-9a81-f4fd92fae421.jpg)
<img width="951" alt="image" src="https://user-images.githubusercontent.com/18474163/175230890-a1645857-9822-474b-b355-2c7fb877aceb.png">
torch的代码在这
https://github.com/TalkUHulk/Image-Animation-Turbo-Boost/blob/main/TPSMM/modules/tpsmm.py

**Comment by hhuiwang** [comment]
> 使用的standard
尴尬的是实在不知道怎么修改才能使用relative模式，不过还是感谢。
