### ISSUE TITLE
TRT and OpenVino model inference

### ISSUE THREAD

**Issue by tayyab-bilal-qs** [TalkUHulk/Image-Animation-Turbo-Boost#2]
I came across your project, however I'm having trouble running inference on the FOMM TRT model you have uploaded on your drive. I suppose it's not the simplified version, if thats so can you please share the simplified onnx trt model.
The error is:
`
[2022-06-23 06:37:07   ERROR] [shuffleNode.cpp::symbolicExecute::387] Error Code 4: Internal Error (Reshape_15: IShuffleLayer applied to shape tensor must have 0 or 1 reshape dimensions: dimensions were [-1,2])
While parsing node number 26 [Pad -> "239"]:
ERROR: ModelImporter.cpp:179 In function parseGraph:
[6] Invalid Node - Pad_26
[shuffleNode.cpp::symbolicExecute::387] Error Code 4: Internal Error (Reshape_15: IShuffleLayer applied to shape tensor must have 0 or 1 reshape dimensions: dimensions were [-1,2])
`
Also I'm getting 8 to 10 minutes of inference time for a 19.37 seconds video on 30 fps using openVINO model created using the script. Could you help resolve the issue?

**Comment by TalkUHulk** [comment]
> 



> I came across your project, however I'm having trouble running inference on the FOMM TRT model you have uploaded on your drive. I suppose it's not the simplified version, if thats so can you please share the simplified onnx trt model. The error is: `[2022-06-23 06:37:07 ERROR] [shuffleNode.cpp::symbolicExecute::387] Error Code 4: Internal Error (Reshape_15: IShuffleLayer applied to shape tensor must have 0 or 1 reshape dimensions: dimensions were [-1,2]) While parsing node number 26 [Pad -> "239"]: ERROR: ModelImporter.cpp:179 In function parseGraph: [6] Invalid Node - Pad_26 [shuffleNode.cpp::symbolicExecute::387] Error Code 4: Internal Error (Reshape_15: IShuffleLayer applied to shape tensor must have 0 or 1 reshape dimensions: dimensions were [-1,2])` Also I'm getting 8 to 10 minutes of inference time for a 19.37 seconds video on 30 fps using openVINO model created using the script. Could you help resolve the issue?

You can find the simplified onnx model  from [Image-Animation-Turbo-Boost](https://github.com/TalkUHulk/Image-Animation-Turbo-Boost).   
<img width="612" alt="image" src="https://user-images.githubusercontent.com/18474163/175233946-5173d9a5-4e56-4b58-8311-e655947c489b.png">

And In my test, time per frame of openVINO is 0.6s. So a 19.37 seconds video on 30 fps need about 15 min.
<img width="407" alt="image" src="https://user-images.githubusercontent.com/18474163/175234044-48623c0c-073a-4176-b7a6-653e93a8dacc.png">

**Comment by tayyab-bilal-qs** [comment]
Thank you so much for your reply, i really appreciate it
I have one more query, during onnx to trt conversion, I faced the following error
![Screenshot from 2022-06-23 12-52-30](https://user-images.githubusercontent.com/98883074/175248838-29b003d5-1c15-4b5e-b331-5082c6e001b5.png)
And when I use the trt model that you provided i get the following error
![Screenshot from 2022-06-23 13-02-58](https://user-images.githubusercontent.com/98883074/175248877-2c5381ad-9bd4-4612-878d-9e895fc2829c.png)

**Comment by TalkUHulk** [comment]
> Thank you so much for your reply, i really appreciate it I have one more query, during onnx to trt conversion, I faced the following error ![Screenshot from 2022-06-23 12-52-30](https://user-images.githubusercontent.com/98883074/175248838-29b003d5-1c15-4b5e-b331-5082c6e001b5.png) And when I use the trt model that you provided i get the following error ![Screenshot from 2022-06-23 13-02-58](https://user-images.githubusercontent.com/98883074/175248877-2c5381ad-9bd4-4612-878d-9e895fc2829c.png)

You may need to re-build trt model in your environment. All my test is on docker[chaoyiyuan/tensorrt8:latest], so the same environment is recommended to use.
<img width="1321" alt="image" src="https://user-images.githubusercontent.com/18474163/175252688-c096cafb-71b2-40ce-9fe5-fe44b9043f3e.png">
