### ISSUE TITLE
made new version including relative mode

### ISSUE THREAD

**Issue by instant-high** [TalkUHulk/Image-Animation-Turbo-Boost#6]
Thank you for your work. Saved me a lot of time.

TPSMM:
Unforunately running inference on CPU is ~50% faster, but running on GPU is ~50% slower than original torch implementation.
Converting to FP16 is working faster but gives weird results...

Nevertheless I modified your export_onnx code and inference code so that it can be run in standard and relative mode.

If someone is interested, you can find it here:
https://github.com/instant-high/Thin_plate_spline_motion_model_-_onnx

**Comment by TalkUHulk** [comment]
> Thank you for your work. Saved me a lot of time.
> 
> TPSMM: Unforunately running inference on CPU is ~50% faster, but running on GPU is ~50% slower than original torch implementation. Converting to FP16 is working faster but gives weird results...
> 
> Nevertheless I modified your export_onnx code and inference code so that it can be run in standard and relative mode.
> 
> If someone is interested, you can find it here: https://github.com/instant-high/Thin_plate_spline_motion_model_-_onnx

Great Job.
I'm glad my work can help you, i will add your code in my reps.
